import type { Metadata } from "next";
import "./globals.css";
import { Work_Sans } from 'next/font/google'
import { Providers } from "./providers";

const workSans = Work_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.className}`}>
        <Providers>
          <div className="h-screen">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
